name: rust-wasm

on: [push, pull_request]

jobs:
  rust-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: .github/actions/rust-wasm
        with:
